language: objective-c
osx_image: xcode7
env:
  - PATH=$PATH:$TRAVIS_BUILD_DIR/node_modules/.bin
git:
  depth: 2
node_js:
  - "0.10"
install:
  - npm install -g ios-sim
  - npm install
script:
  - cordova-paramedic --platform ios --plugin ${TRAVIS_BUILD_DIR}
